spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chethanks545@gmail.com
    password: ywwl kzgi cgty tplg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/Mails
    username: postgres
    password: Venom07%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

